baseURL = 'https://coderdojobrighton.github.io/python-flappy-bird'
title = 'Flappy Bird'
theme = "hugo-book"

[markup]
[markup.goldmark.renderer]
    unsafe = true

[menu]


# See details at https://github.com/alex-shpak/hugo-book
[params]
    BookTheme = 'light'
    BookToC = false
    BookSearch = false
    BookComments = false
    xBookLogo = "favicon.png"
    BookSection = 'docs'
